# Generated by Django 4.1.7 on 2023-12-01 23:40

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=4)),
                ('top_notes', models.TextField(blank=True, null=True)),
                ('middle_notes', models.TextField(blank=True, null=True)),
                ('base_notes', models.TextField(blank=True, null=True)),
                ('olfactory_family', models.TextField(blank=True, null=True)),
                ('love', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('hate', models.IntegerField(default=0)),
                ('winter', models.IntegerField(default=0)),
                ('spring', models.IntegerField(default=0)),
                ('summer', models.IntegerField(default=0)),
                ('fall', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('rating_votes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('EAN', models.IntegerField(default=0)),
                ('fragrantica_url', models.TextField(blank=True, null=True)),
                ('sephora_uk_url', models.TextField(blank=True, null=True)),
                ('perfumesclub_uk_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
