# Generated by Django 4.1.7 on 2023-12-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='accords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
