# Generated by Django 4.1.7 on 2023-12-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
