# Generated by Django 4.1.7 on 2024-01-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_perfume_description_perfume_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('store_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('store_url', models.CharField(blank=True, max_length=100, null=True)),
                ('ean', models.IntegerField(blank=True, null=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='rest.perfume')),
            ],
        ),
    ]
