# Generated by Django 4.1.7 on 2024-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_perfumesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
