# Generated by Django 4.1.7 on 2024-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_brand_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='perfumes',
            field=models.IntegerField(default=0),
        ),
    ]
