# Generated by Django 4.1.7 on 2024-01-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_perfume_le_nez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='EAN',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='perfumesclub_uk_url',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='sephora_uk_url',
        ),
        migrations.AddField(
            model_name='perfume',
            name='similar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='le_nez',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
