# Generated by Django 4.1.7 on 2024-01-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_remove_perfume_ean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='day',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='fall',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='hate',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='like',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='love',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='night',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='rating_votes',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='spring',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='summer',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='winter',
        ),
    ]
